name: Test Coverage

on: [ "push", "pull_request" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: yarn install
      - run: yarn test-coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: codecov/codecov-action@v1
        with:
          directory: ./coverage/
          verbose: true # optional (default = false)
